apiVersion: v1
kind: List
metadata:
  name: razeedash-deployment
  namespace: razee
  annotations:
    version: "{{TRAVIS_COMMIT}}"
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        version: "{{TRAVIS_COMMIT}}"
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      name: razeedash
      namespace: razee
    spec:
      replicas: 6
      revisionHistoryLimit: 0
      selector:
        matchLabels:
          app: razeedash
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: razeedash
          name: razeedash
        spec:
          containers:
          - env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: razeedash-secret
                  key: mongo_url
            - name: OAUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: razeedash-secret
                  key: oauth_secret_key
                  optional: true
            - name: GITHUB_URL
              value: "https://github.com/"
            - name: GITHUB_API
              value: "https://api.github.com/"
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: razeedash-config
                  key: root_url
            - name: app_name
              value: Razeedash
            image: "quay.io/razee/razeedash:{{TRAVIS_TAG}}"
            imagePullPolicy: Always
            name: razeedash
            ports:
            - containerPort: 80
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /login
                port: 80
              initialDelaySeconds: 3
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /login
                port: 80
              initialDelaySeconds: 3
              periodSeconds: 20
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: razeedash-service
      name: razeedash-service
      namespace: razee
    spec:
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
      selector:
        app: razeedash
