apiVersion: v1
kind: List
metadata:
  name: razeedash-deployment
  namespace: razee
  annotations:
    version: "{{TRAVIS_COMMIT}}"
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
type: array
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        version: "{{TRAVIS_COMMIT}}"
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      name: razeedash
      namespace: razee
    spec:
      replicas: 1
      revisionHistoryLimit: 0
      selector:
        matchLabels:
          app: razeedash
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: razeedash
          name: razeedash
        spec:
          containers:
          - env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: razeedash-secret
                  key: mongo_url
            - name: OAUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: razeedash-secret
                  key: oauth_secret_key
                  optional: true
            - name: GITHUB_URL
              value: "https://github.com/"
            - name: GITHUB_API
              value: "https://api.github.com/"
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: razeedash-config
                  key: root_url
            - name: RAZEEDASH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: razeedash-config
                  key: razeedash_api_url
                  optional: true
            - name: app_name
              value: Razeedash
            image: "quay.io/razee/razeedash:{{TRAVIS_TAG}}"
            imagePullPolicy: Always
            name: razeedash
            ports:
            - containerPort: 3000
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /login
                port: 3000
              initialDelaySeconds: 3
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /login
                port: 3000
              initialDelaySeconds: 3
              periodSeconds: 20
            resources:
              requests:
                cpu: 100m
                memory: 80Mi
              limits:
                cpu: 500m
                memory: 256Mi
